#Requires -Version 5.1
<#
.SYNOPSIS
  Regenerates the snapshot registry and panel data file.
  Called automatically by Create-Snapshot.ps1 and Restore-Snapshot.ps1.
#>

$SnapshotsRoot = $PSScriptRoot
$projectsJsonPath = Join-Path $SnapshotsRoot "projects.json"
$projectsList = @()

if (Test-Path $projectsJsonPath) {
    try {
        $projsObj = Get-Content $projectsJsonPath -Raw | ConvertFrom-Json
        foreach ($p in $projsObj) {
            if ($p.name -and $p.path -and (Test-Path $p.path)) {
                $projectsList += [PSCustomObject]@{
                    Name = $p.name
                    Path = (Resolve-Path $p.path).Path
                }
            }
        }
    } catch {
        Write-Warning "Failed to parse projects.json in Refresh-Registry: $_"
    }
}

# Fallback projects list
$fallbackProjects = @{
    "mypools"   = "C:\Podman\MyPools"
    "ESSOP"     = "C:\ESSOP"
}

foreach ($key in $fallbackProjects.Keys) {
    if (-not ($projectsList | Where-Object { $_.Name -eq $key })) {
        $pPath = $fallbackProjects[$key]
        if (Test-Path $pPath) {
            $projectsList += [PSCustomObject]@{
                Name = $key
                Path = (Resolve-Path $pPath).Path
            }
        }
    }
}

$registry = @{}
foreach ($proj in $projectsList) {
    $projName = $proj.Name
    $projPath = $proj.Path

    $snapsPath = Join-Path $projPath "Snapshots"
    $legacySnapsPath = Join-Path $projPath ".snapshots"
    
    $snapshotsDirs = @()
    if (Test-Path $snapsPath) {
        $snapshotsDirs += Get-ChildItem -Path $snapsPath -Directory -ErrorAction SilentlyContinue
    }
    if (Test-Path $legacySnapsPath) {
        $snapshotsDirs += Get-ChildItem -Path $legacySnapsPath -Directory -ErrorAction SilentlyContinue
    }

    $uniqueSnapshots = @{}
    foreach ($snap in $snapshotsDirs) {
        if (Test-Path (Join-Path $snap.FullName "snapshot.json")) {
            if (-not $uniqueSnapshots.ContainsKey($snap.Name)) {
                $uniqueSnapshots[$snap.Name] = $snap
            }
        }
    }
    
    $snapshots = @($uniqueSnapshots.Values | Sort-Object Name -Descending)


    $projData = @{
        name = $projName
        source_path = $projPath
        snapshots = @()
    }

    foreach ($snap in $snapshots) {
        $jsonPath = Join-Path $snap.FullName "snapshot.json"
        try {
            $meta = Get-Content $jsonPath -Raw | ConvertFrom-Json
            if ($meta.source_path) {
                $projData.source_path = $meta.source_path
            }
            $hasDb = Test-Path (Join-Path $snap.FullName "database.sql")
            $hasZip = Test-Path (Join-Path $snap.FullName "project.zip")
            
            $projData.snapshots += @{
                name = $snap.Name
                timestamp = $meta.timestamp
                description = $meta.description
                files_count = $meta.files_count
                database_included = $hasDb
                files_included = $hasZip
                powered_off = $meta.powered_off_snapshot
                git_commit = $meta.git_commit
                git_branch = $meta.git_branch
                source_path = $projData.source_path
                backup_level = $meta.backup_level
            }
        } catch {
            Write-Warning "Skipping $($snap.Name): invalid snapshot.json"
        }
    }

    $registry[$projName] = $projData
}

# Write registry.json (machine-readable)
$registry | ConvertTo-Json -Depth 5 | Out-File -FilePath (Join-Path $SnapshotsRoot "registry.json") -Encoding UTF8

# Write snapshots-data.js (for panel.ps1)
$jsData = "// Auto-generated by Refresh-Registry.ps1 - do not edit`n// Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n`nwindow.__SNAPSHOT_REGISTRY__ = " + ($registry | ConvertTo-Json -Depth 5 -Compress) + ";`n"
$jsData | Out-File -FilePath (Join-Path $SnapshotsRoot "snapshots-data.js") -Encoding UTF8

Write-Host "Registry updated: $($projectsList.Count) projects, $($registry.Values | ForEach-Object { $_.snapshots.Count } | Measure-Object -Sum | Select-Object -ExpandProperty Sum) snapshots total." -ForegroundColor Green
