#Requires -Version 5.1
<#
.SYNOPSIS
  Regenerates the snapshot registry and panel data file.
  Called automatically by Create-Snapshot.ps1 and Restore-Snapshot.ps1.
#>

$SnapshotsRoot = "C:\snapshots"
$ProjectsFile = Join-Path $SnapshotsRoot "projects.json"

$projectsList = @()
if (Test-Path $ProjectsFile) {
    try {
        $raw = Get-Content $ProjectsFile -Raw | ConvertFrom-Json
        if ($raw -is [Array]) {
            $projectsList = $raw
        } elseif ($raw -ne $null) {
            $projectsList = @($raw)
        }
    } catch {
        Write-Warning "Failed to parse projects.json. Falling back to directory scan."
    }
}

if ($projectsList.Count -eq 0) {
    # Legacy fallback: Scan subdirectories under C:\snapshots
    $projectsList = @(Get-ChildItem -Path $SnapshotsRoot -Directory -ErrorAction SilentlyContinue | Where-Object {
        $_.Name -notmatch '^(templates|_archive|public|tools)$'
    } | ForEach-Object {
        [PSCustomObject]@{
            name = $_.Name
            path = $_.FullName
        }
    })
}

$registry = @{}
foreach ($proj in $projectsList) {
    $projName = $proj.name
    $projPath = $proj.path

    # Try local .snapshots folder first
    $snapsPath = Join-Path $projPath ".snapshots"
    if (-not (Test-Path $snapsPath)) {
        # Fallback to C:\snapshots\<ProjectName>
        $snapsPath = Join-Path $SnapshotsRoot $projName
    }

    $snapshots = @(Get-ChildItem -Path $snapsPath -Directory -ErrorAction SilentlyContinue | Where-Object {
        Test-Path (Join-Path $_.FullName "snapshot.json")
    } | Sort-Object Name -Descending)

    $projData = @{
        name = $projName
        source_path = $projPath
        snapshots = @()
    }

    foreach ($snap in $snapshots) {
        $jsonPath = Join-Path $snap.FullName "snapshot.json"
        try {
            $meta = Get-Content $jsonPath -Raw | ConvertFrom-Json
            $sourcePathVal = if ($meta.source_path) { $meta.source_path } else { $projPath }
            $projData.source_path = $sourcePathVal
            
            $hasDb = Test-Path (Join-Path $snap.FullName "database.sql")
            $hasZip = Test-Path (Join-Path $snap.FullName "project.zip")
            
            $projData.snapshots += @{
                name = $snap.Name
                timestamp = $meta.timestamp
                description = $meta.description
                files_count = $meta.files_count
                database_included = $hasDb
                files_included = $hasZip
                powered_off = $meta.powered_off_snapshot
                git_commit = $meta.git_commit
                git_branch = $meta.git_branch
                source_path = $sourcePathVal
            }
        } catch {
            Write-Warning "Skipping $($snap.Name): invalid snapshot.json"
        }
    }

    $registry[$projName] = $projData
}

# Write registry.json (machine-readable)
$registry | ConvertTo-Json -Depth 5 | Out-File -FilePath (Join-Path $SnapshotsRoot "registry.json") -Encoding UTF8

# Write snapshots-data.js (for panel.ps1)
$jsData = "// Auto-generated by Refresh-Registry.ps1 - do not edit`n// Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n`nwindow.__SNAPSHOT_REGISTRY__ = " + ($registry | ConvertTo-Json -Depth 5 -Compress) + ";`n"
$jsData | Out-File -FilePath (Join-Path $SnapshotsRoot "snapshots-data.js") -Encoding UTF8

Write-Host "Registry updated: $($projectsList.Count) projects, $($registry.Values | ForEach-Object { $_.snapshots.Count } | Measure-Object -Sum | Select-Object -ExpandProperty Sum) snapshots total." -ForegroundColor Green
